# Generated by Django 5.1.6 on 2025-02-26 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bhaiimodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para_name', models.CharField(blank=True, max_length=20, null=True)),
                ('para_address', models.TextField(blank=True, null=True)),
                ('para_ph_no', models.IntegerField(null=True)),
                ('para_ac_brand', models.CharField(blank=True, max_length=30, null=True)),
                ('para_ac_issue', models.CharField(blank=True, max_length=30, null=True)),
                ('para_service_date', models.DateField(blank=True, null=True)),
                ('para_nxt_service_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
