# Generated by Django 5.1.6 on 2025-03-01 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nuhachillcare', '0002_alter_bhaiimodel_para_ac_brand_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bhaiimodel',
            name='para_ac_brand',
            field=models.CharField(blank=True, choices=[('Daikin', 'daikin'), ('Samsung', 'samsung'), ('Bluestar', 'bluestar'), ('Whirlpool', 'whirlpool'), ('Others', 'others')], max_length=30, null=True),
        ),
    ]
