# Generated by Django 5.1.6 on 2025-03-10 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Nuhachillcare', '0003_alter_bhaiimodel_para_ac_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhaiimodel',
            name='para_service_charges',
            field=models.IntegerField(null=True),
        ),
    ]
